---
page-title: Berserk Studios
ios-app-id: ''
appstore-link: https://apps.apple.com/us/app/itunes-remote/id284417350
playstore-link: https://play.google.com/store/apps/details?id=air.au.com.metro.DumbWaysToDie2
presskit-title: Kit
presskit-download-link: https://google.com
app-icon: assets/appicon.png
app-name: Web Connect
app-price: US $50
app-description: Web app for the absent minded
enable-smart-app-banner: true
footer-description: Made by Jane smith in Toronto
contact-list:
- url: https://twitter.com/john.doe
  icon: user
- url: https://github.com/john.doe
  icon: user
- url: mailto:john.doe@gmail.com
  icon: user
features-list:
- title: Support
  description: Lorem ipsum
  fontawesome-icon-name: glass
- title: Support
  description: Lorem ipsum
  fontawesome-icon-name: glass
- title: Support
  description: Lorem ipsum
  fontawesome-icon-name: glass
- title: Tune
  description: Lorem ipsum
  fontawesome-icon-name: music
- title: Tune
  description: Lorem ipsum
  fontawesome-icon-name: music
- title: Tune
  description: Lorem ipsum
  fontawesome-icon-name: music
- title: Search
  description: Lorem ipsum
  fontawesome-icon-name: search
- title: Search
  description: Lorem ipsum
  fontawesome-icon-name: search
- title: Search
  description: Lorem ipsum
  fontawesome-icon-name: search
topbar-color: "#000000"
topbar-transparency: '0.1'
topbar-title-color: "#ffffff"
cover-image: assets/headerimage.png
cover-overlay-color: "#363b3d"
cover-overlay-transparency: '0.8'
device-color: black
body-background-color: "#ffffff"
link-color: "#1d63ea"
app-title-color: "#ffffff"
app-price-color: "#ffffff"
app-description-color: "#ffffff"
feature-title-color: "#000000"
feature-text-color: "#666666"
feature-icons-foreground-color: "#1d63ea"
feature-icons-background-color: "#e6e6e6"
social-icons-foreground-color: "#666666"
social-icons-background-color: "#e6e6e6"
footer-text-color: "#666666"
sass:
  style: compressed
collections:
  pages:
    output: true
    permalink: "/:path/"
markdown: kramdown
url: https://heydavid-dev.github.io
baseurl: "/automatic-8-277"
